name: Airflow github actions

on:
  push:
    # types: [opened, synchronize, reopened]
    branches:
      - staging
      - main

jobs:
  test:
    name: Run pre-commit and tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: 'Test Airflow DAGs'
      uses: micael-grilo/airflow-dags-test-action@v2.10.1
      with:
        requirements-file: ./requirements.txt
        dags-path: ./dags
        error-comment: True
        var-file: ./empty.json