name: Airflow GitHub Actions

on:
  push:
    branches:
      - staging
      - main

jobs:
  test:
    name: Run pre-commit and tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: List DAG Files
      run: ls -R ./dags

    - name: Validate DAG Syntax
      run: python -m py_compile $(find ./dags -name "*.py")

    - name: Test Airflow DAGs
      uses: micael-grilo/airflow-dags-test-action@v2.10.1
      with:
        requirements-file: ./requirements.txt
        dags-path: ./dags
        error-comment: True
        var-file: ./var.json
        dags-test-folder: ./tests
